# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
project_name: mask
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -X github.com/ThorstenHans/mask/cmd.Version={{.Version}}
    goos:
      - linux
      - windows
      - darwin
archives:
  - format: tar.gz
    name_template: "{{ .ProjectName}}_{{ .Os}}_{{ .Arch}}_{{ .Version}}"
    format_overrides:
      - goos: windows
        format: zip
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
release:
  github:
    owner: ThorstenHans
    name: mask
  mode: prepend

